-- Add missing columns to Patients table if they don't exist
-- This migration script adds the patient detail columns required by the application

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'Email')
BEGIN
	ALTER TABLE Patients ADD Email NVARCHAR(100) DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'BloodGroup')
BEGIN
	ALTER TABLE Patients ADD BloodGroup NVARCHAR(10) DEFAULT 'Unknown';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'AddressLine1')
BEGIN
	ALTER TABLE Patients ADD AddressLine1 NVARCHAR(255) DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'City')
BEGIN
	ALTER TABLE Patients ADD City NVARCHAR(100) DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'EmergencyName')
BEGIN
	ALTER TABLE Patients ADD EmergencyName NVARCHAR(100) DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'EmergencyPhone')
BEGIN
	ALTER TABLE Patients ADD EmergencyPhone NVARCHAR(15) DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Patients' AND COLUMN_NAME = 'MedicalHistory')
BEGIN
	ALTER TABLE Patients ADD MedicalHistory NVARCHAR(MAX) DEFAULT '';
END
