-- Add missing columns to patient table
-- Run this script in SQL Server to update the dbo.dbPatient table

-- Check if columns exist and add them if they don't
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='BloodGroup')
	ALTER TABLE dbo.dbPatient ADD BloodGroup NVARCHAR(10) DEFAULT 'Unknown';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='Email')
	ALTER TABLE dbo.dbPatient ADD Email NVARCHAR(100) DEFAULT '';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='AddressLine1')
	ALTER TABLE dbo.dbPatient ADD AddressLine1 NVARCHAR(255) DEFAULT '';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='City')
	ALTER TABLE dbo.dbPatient ADD City NVARCHAR(100) DEFAULT '';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='EmergencyName')
	ALTER TABLE dbo.dbPatient ADD EmergencyName NVARCHAR(100) DEFAULT '';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='EmergencyPhone')
	ALTER TABLE dbo.dbPatient ADD EmergencyPhone NVARCHAR(20) DEFAULT '';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dbPatient' AND COLUMN_NAME='MedicalHistory')
	ALTER TABLE dbo.dbPatient ADD MedicalHistory NVARCHAR(MAX) DEFAULT '';

-- Verify the columns were added
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME='dbPatient' 
ORDER BY ORDINAL_POSITION;
